### ISSUE TITLE
make library and provide as NuGet package

### ISSUE THREAD

**Issue by MagicAndre1981** [lowleveldesign/send2procmon#1]
This is a fantastic find to add own events to procmon. 

Can you please put this into a library and provide it as NuGet package for easy usage in own code?

**Comment by lowleveldesign** [comment]
@MagicAndre1981 I will, in the meantime you may have a look at https://github.com/Wintellect/ProcMonDebugOutput. They don't have nugets unfortunately.

**Comment by lowleveldesign** [comment]
@MagicAndre1981 Nuget package available: https://www.nuget.org/packages/Send2Procmon/. I'm closing the ticket.
